import type { TablaContrato } from '../types/esquema';

export const tablasContrato: TablaContrato[] = [
  'roles',
  'permisos',
  'rol_permisos',
  'usuarios',
  'sucursales',
  'configuracion_empresa',
  'clientes',
  'direcciones_clientes',
  'categorias',
  'subcategorias',
  'productos',
  'variantes_productos',
  'imagenes_productos',
  'etiquetas',
  'producto_etiquetas',
  'promociones',
  'reglas_promocion',
  'pedidos',
  'detalle_pedidos',
  'metodos_pago',
  'pagos',
  'ingresos',
  'gastos',
  'proveedores',
  'insumos',
  'movimientos_inventario',
  'compras',
  'detalle_compras',
  'producciones',
  'recetas',
  'detalle_recetas',
  'repartidores',
  'entregas',
  'alertas',
  'notificaciones',
  'metricas_dashboard',
  'predicciones_ventas',
];

export const vistasContrato = ['vista_pedidos_detalle', 'vista_costeo_productos', 'vista_resumen_dashboard'] as const;

export const columnasPrincipales: Record<TablaContrato, string[]> = {
  roles: ['id', 'nombre', 'activo'],
  permisos: ['id', 'codigo', 'modulo'],
  rol_permisos: ['id', 'rol_id', 'permiso_id'],
  usuarios: ['id', 'rol_id', 'nombres', 'email', 'activo'],
  sucursales: ['id', 'nombre', 'direccion', 'activa'],
  configuracion_empresa: ['id', 'nombre_comercial', 'whatsapp', 'moneda'],
  clientes: ['id', 'nombres', 'telefono', 'activo'],
  direcciones_clientes: ['id', 'cliente_id', 'direccion', 'principal'],
  categorias: ['id', 'nombre', 'activa'],
  subcategorias: ['id', 'categoria_id', 'nombre', 'activa'],
  productos: ['id', 'categoria_id', 'nombre', 'precio_venta', 'margen', 'disponible', 'destacado'],
  variantes_productos: ['id', 'producto_id', 'nombre', 'stock', 'activa'],
  imagenes_productos: ['id', 'producto_id', 'url', 'principal'],
  etiquetas: ['id', 'nombre', 'color'],
  producto_etiquetas: ['id', 'producto_id', 'etiqueta_id'],
  promociones: ['id', 'nombre', 'codigo', 'tipo_descuento', 'activa'],
  reglas_promocion: ['id', 'promocion_id', 'monto_minimo'],
  pedidos: ['id', 'cliente_id', 'codigo', 'estado', 'total'],
  detalle_pedidos: ['id', 'pedido_id', 'nombre_producto', 'cantidad', 'subtotal'],
  metodos_pago: ['id', 'nombre', 'activo'],
  pagos: ['id', 'pedido_id', 'metodo_pago_id', 'monto', 'estado'],
  ingresos: ['id', 'categoria', 'descripcion', 'monto', 'fecha'],
  gastos: ['id', 'categoria', 'descripcion', 'monto', 'fecha'],
  proveedores: ['id', 'nombre', 'telefono', 'activo'],
  insumos: ['id', 'nombre', 'unidad_medida', 'stock_actual', 'stock_minimo'],
  movimientos_inventario: ['id', 'insumo_id', 'tipo', 'cantidad', 'motivo'],
  compras: ['id', 'proveedor_id', 'codigo', 'estado', 'total'],
  detalle_compras: ['id', 'compra_id', 'insumo_id', 'cantidad', 'subtotal'],
  producciones: ['id', 'producto_id', 'codigo', 'estado', 'cantidad_planificada'],
  recetas: ['id', 'producto_id', 'nombre', 'rendimiento', 'costo_estimado'],
  detalle_recetas: ['id', 'receta_id', 'insumo_id', 'cantidad'],
  repartidores: ['id', 'nombres', 'telefono', 'activo'],
  entregas: ['id', 'pedido_id', 'repartidor_id', 'estado', 'costo'],
  alertas: ['id', 'tipo', 'titulo', 'nivel', 'leida'],
  notificaciones: ['id', 'usuario_id', 'titulo', 'leida'],
  metricas_dashboard: ['id', 'fecha', 'ventas_totales', 'pedidos_totales'],
  predicciones_ventas: ['id', 'producto_id', 'fecha_objetivo', 'cantidad_estimada'],
};
